tap "homebrew/bundle"
tap "homebrew/services"

# Shared formulae — installable by Homebrew on both macOS and Linux.
# macOS-only entries (casks, VSCode extensions) live in Brewfile.mac.
brew "atuin"
brew "bat"
brew "direnv"
brew "dysk"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "glab"
brew "lazygit"
brew "ncdu"
brew "nvim"
brew "nvm"
brew "pyenv"
brew "ripgrep"
brew "shellcheck"
brew "speedtest-cli"
brew "tealdeer"
brew "tig"
brew "tmux"
brew "tmuxinator"
brew "trash-cli"
brew "ugrep"
brew "yq"
brew "zoxide"
