set nocompatible " Never allow compatibility mode with vi

" Vundle and plugins
filetype off " Required for Vundle

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle
Bundle "gmarik/vundle"


" Hybrid for syntax highlighting
Bundle 'w0ng/vim-hybrid'

" Airline instead of powerline because it's faster
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
let g:airline_powerline_fonts = 1
let g:airline_theme='powerlineish'

" Done with Vundle and bundles
call vundle#end()
filetype plugin indent on



set modeline

set incsearch
set ignorecase
set smartcase

syntax on

set laststatus=2
