set nocompatible " Never allow compatibility mode with vi

" Vundle and plugins
filetype off " Required for Vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle
Bundle "gmarik/vundle"


set modeline

set incsearch
set ignorecase
set smartcase

filetype plugin indent on
syntax on

source /usr/local/lib/python2.7/site-packages/powerline/bindings/vim/plugin/powerline.vim
set laststatus=2
